object Versions {

    const val KOTLIN = "1.4.32"
    const val KTX = "1.3.2"
    const val APPCOMPAT = "1.2.0"
    const val RETROFIT = "2.9.0"
    const val MATERIAL = "1.3.0"
    const val CONSTRAINT = "2.0.4"
    const val GSON_CONVERTER = "2.7.1"
    const val GSON = "2.8.6"
    const val JUNIT = "4.+"
    const val JUNIT_EXT = "1.1.2"
    const val ESPRESSO = "3.3.0"
    const val GLIDE = "4.12.0"
    const val DAGGER = "2.34.1"
    const val ROOM = "2.3.0"
    const val RXJAVA = "2.2.11"
    const val RXJAVA_ANDROID = "2.1.1"
    const val RXJAVA_KOTLIN = "2.4.0"
    const val RXJAVA_ADAPTER = "2.6.1"
    const val RXJAVA_ADAPTER_JAKE = "1.0.0"
    const val MOCKK = "1.11.0"
    const val FRAG_KTX = "1.3.3"
    const val CHUCK = "1.1.0"
    const val LOGGING = "4.9.1"
    const val PALETTE = "1.0.0"
}